server:
  applicationConnectors:
    - type: http
      port: 3001
      idleTimeout: 1000 seconds

logging:
  level: INFO

database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: appuser
  password: StrongP@ssw0rd!
  url: jdbc:mysql://127.0.0.1:3306/search_assessment
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQLDialect
  maxWaitForConnection: 1s
  validationQuery: "/* MyApplication Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false

airtableServer:
  protocol: https
  host: api.airtable.com
  port: 443
  token: patmufRxHetPY3l2d.37cd144946b7b3d919273c52e53d76c79176d830444d9f69bfea3e7b4118d792
  termsBaseId: appbVw1fwzUCMa0Vh
  archiveBaseId: appfJD8VSNmCf19Tg

httpClient:
  timeout: 5000ms
  connectionTimeout: 5000ms
  timeToLive: 1 hour
  cookiesEnabled: false
  maxConnections: 1024
  maxConnectionsPerRoute: 1024
  keepAlive: 0s

searchPage:
  globalEn: https://www.canada.ca/en/sr/srb.html
  globalFr: https://www.canada.ca/fr/sr/srb.html
  google: https://www.google.ca/search
